/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#FBBF24',
          light: '#FCD34D',
          dark: '#F59E0B',
        },
        secondary: {
          DEFAULT: '#F59E0B',
          light: '#FBBF24',
          dark: '#D97706',
        },
        accent: '#EF4444',
        gold: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        dark: {
          50: '#f8fafc',
          100: '#e2e8f0',
          200: '#cbd5e1',
          300: '#94a3b8',
          400: '#64748b',
          500: '#475569',
          600: '#334155',
          700: '#1e293b',
          800: '#0f172a',
          900: '#020617',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        heading: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 2s infinite',
        'float-slow': 'float 8s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'slide-up': 'slideUp 0.6s ease-out',
        'slide-up-delayed': 'slideUp 0.6s ease-out 0.2s both',
        'fade-in': 'fadeIn 0.8s ease-out',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'gradient': 'gradient 8s ease infinite',
        'aurora': 'aurora 15s ease-in-out infinite',
        'aurora-alt': 'aurora 20s ease-in-out infinite reverse',
        'aurora-slow': 'aurora 25s ease-in-out infinite',
        'particle-1': 'particleFloat1 20s linear infinite',
        'particle-2': 'particleFloat2 25s linear infinite',
        'particle-3': 'particleFloat3 18s linear infinite',
        'particle-4': 'particleFloat4 22s linear infinite',
        'particle-5': 'particleFloat5 30s linear infinite',
        'twinkle': 'twinkle 3s ease-in-out infinite',
        'drift': 'drift 20s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px) scale(1)' },
          '50%': { transform: 'translateY(-25px) scale(1.05)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 20px rgba(99, 102, 241, 0.3)' },
          '100%': { boxShadow: '0 0 60px rgba(99, 102, 241, 0.6), 0 0 100px rgba(99, 102, 241, 0.3)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        gradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        aurora: {
          '0%': { backgroundPosition: '0% 50%', transform: 'rotate(0deg) scale(1)' },
          '25%': { backgroundPosition: '50% 100%', transform: 'rotate(5deg) scale(1.1)' },
          '50%': { backgroundPosition: '100% 50%', transform: 'rotate(0deg) scale(1)' },
          '75%': { backgroundPosition: '50% 0%', transform: 'rotate(-5deg) scale(1.1)' },
          '100%': { backgroundPosition: '0% 50%', transform: 'rotate(0deg) scale(1)' },
        },
        particleFloat1: {
          '0%': { transform: 'translate(0vw, 100vh) scale(0)', opacity: '0' },
          '10%': { opacity: '1', transform: 'translate(1vw, 90vh) scale(1)' },
          '90%': { opacity: '1', transform: 'translate(-5vw, 10vh) scale(1)' },
          '100%': { transform: 'translate(-2vw, 0vh) scale(0)', opacity: '0' },
        },
        particleFloat2: {
          '0%': { transform: 'translate(0vw, 100vh) scale(0)', opacity: '0' },
          '10%': { opacity: '0.8', transform: 'translate(-3vw, 85vh) scale(1)' },
          '90%': { opacity: '0.8', transform: 'translate(4vw, 15vh) scale(1)' },
          '100%': { transform: 'translate(2vw, 5vh) scale(0)', opacity: '0' },
        },
        particleFloat3: {
          '0%': { transform: 'translate(0vw, 100vh) scale(0)', opacity: '0' },
          '10%': { opacity: '0.6', transform: 'translate(5vw, 80vh) scale(1)' },
          '90%': { opacity: '0.6', transform: 'translate(-2vw, 20vh) scale(1)' },
          '100%': { transform: 'translate(1vw, 10vh) scale(0)', opacity: '0' },
        },
        particleFloat4: {
          '0%': { transform: 'translate(0vw, 100vh) scale(0)', opacity: '0' },
          '10%': { opacity: '0.7', transform: 'translate(-4vw, 95vh) scale(1)' },
          '90%': { opacity: '0.7', transform: 'translate(3vw, 5vh) scale(1)' },
          '100%': { transform: 'translate(-1vw, 0vh) scale(0)', opacity: '0' },
        },
        particleFloat5: {
          '0%': { transform: 'translate(0vw, 100vh) scale(0)', opacity: '0' },
          '10%': { opacity: '0.5', transform: 'translate(2vw, 88vh) scale(1)' },
          '90%': { opacity: '0.5', transform: 'translate(-3vw, 12vh) scale(1)' },
          '100%': { transform: 'translate(0vw, 8vh) scale(0)', opacity: '0' },
        },
        twinkle: {
          '0%, 100%': { opacity: '0.2', transform: 'scale(0.8)' },
          '50%': { opacity: '1', transform: 'scale(1.2)' },
        },
        drift: {
          '0%, 100%': { transform: 'translateX(0) translateY(0)' },
          '25%': { transform: 'translateX(10px) translateY(-10px)' },
          '50%': { transform: 'translateX(-5px) translateY(5px)' },
          '75%': { transform: 'translateX(-10px) translateY(-5px)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
};
